### ISSUE TITLE
ログイン試行時、HTTPコード 500 を返され、ログインができない

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/lottery-backend#18]
Chromeからのアクセスの場合はエラーログなしで500を返し、`wuzz`からのアクセス時には時たま以下のエラーを吐きます。

```
backend_1   | Traceback (most recent call last):
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
backend_1   |     return self.wsgi_app(environ, start_response)
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
backend_1   |     response = self.handle_exception(e)
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
backend_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
backend_1   |     reraise(exc_type, exc_value, tb)
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
backend_1   |     raise value
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
backend_1   |     response = self.full_dispatch_request()
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
backend_1   |     rv = self.handle_user_exception(e)
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
backend_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
backend_1   |     reraise(exc_type, exc_value, tb)
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
backend_1   |     raise value
backend_1   |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
backend_1   |     rv = self.dispatch_request()
backend_1   |   File "/root/.local/shbackend_1   |   File "/root/.local/shbackend_1   |   File "/root/.local/shbackend_1   |   File "/root/.local/shbackend_1   |   File "/root/.locaiobackend_1   |   File "/root/.local/shbackend_1   | File "/code/api/routes/auth.py", line 28, in home
backend_1   |     return jsonify({"message": "Login Successful"},token=token.decode())
backend_1   |   backend_1   |   backend_1   |   backend_1   |   backend_1   |   backend_1   |   bask/json/__init__.py", line 314, in jsonify
backend_1   |     raise TypeError('jsonify() behavior undefined when passed both args and kwargs')
backend_1   | TypeError: jsonify() behavior undefined when passed both args and kwargs
```

主な問題としては、
`backend_1   | TypeError: jsonify() behavior undefined when passed both args and kwargs`
ここのようです。

**Comment by Cj-bc** [comment]
解決しました。
`args`と`kwargs`を同時に取れない=引数が二つ取ることができないということであろうと思ったので試したらうまく行きました。
変更箇所: https://github.com/Sakuten/lottery-backend/blob/develop/api/routes/auth.py#28-29

変更点:
```
-            return jsonify({"message": "Login Successful"},
-                           token=token.decode())
+            return jsonify({"message": "Login Successful","token": token.decode()})
```

**Comment by Cj-bc** [comment]
PR作成しました
https://github.com/Sakuten/lottery-backend/issues/18

**Comment by coord-e** [comment]
Merged #19
